Added Coq proof output

diff --git a/tests/proof/run b/tests/proof/run
--- a/tests/proof/run
+++ b/tests/proof/run
@@ -4,8 +4,12 @@
 
 for f in `find ./ -type f -path "*/*.*" | sort`; do
 
-  if ! ../../archsat --infer $f --coq proof.v > log; then
+  if ! ../../archsat -x +meta --meta.find=auto --infer $f --coq proof.v > log; then
     echo -e "\e[1;31m[FAIL]\e[0m $f (prover run)"
+    exit 1
+  fi
+  if ! grep Unsat log > /dev/null; then
+    echo -e "\e[1;31m[ERROR]\e[0m $f (not unsat)"
     exit 1
   fi
   if ! coqc proof.v; then
